version: '3.8'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - ./postgres/:/var/lib/postgresql/data:rw
    networks:
      system:
        ipv4_address: 192.168.221.2

  app:
    container_name: app
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app/
      - ./php/php.ini:/usr/local/etc/php/php.ini
#      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-intl.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.221.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=PhpServerBase"
    networks:
      system:
        ipv4_address: 192.168.221.3
    extra_hosts:
      - "host.docker.internal:192.168.221.1"

  nginx_:
    container_name: nginx_
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/app/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app
      - db
    networks:
      system:
        ipv4_address: 192.168.221.4

networks:
  system:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/24